INST_COMMAND=['sudo',
         'zypper',
         '--non-interactive',
         'install',
         '--auto-agree-with-licenses'
        ]
STEAMCMD=[*INST_COMMAND,'steamcmd']
DHEWM3=[*INST_COMMAND,'dhewm3']
QUAKESPASM=[*INST_COMMAND,'quakespasm']
DSDADOOM=[*INST_COMMAND,'dsda-doom']
DUNELEGACY=[*INST_COMMAND,'dunelegacy']
FHEROES2=[*INST_COMMAND,'fheroes2']
OPENTYRIAN=[*INST_COMMAND,'opentyrian']
XRICK=[*INST_COMMAND,'xrick']
OPENXCOM=[*INST_COMMAND,'openxcom']
SCUMMVM=[*INST_COMMAND,'scummvm']
REMINISCENCE=[*INST_COMMAND,'reminiscence']
#
ADD_REP_COMMAND=['sudo','zypper','ar']
ADD_FHEROES2_REP=[*ADD_REP_COMMAND,
                  'https://download.opensuse.org/repositories/games/openSUSE_Tumbleweed/',
                  'games-openSUSE_Tumbleweed']
